package com.connect.meetupsfellow.constants

/**
 * Created by Maheshwar on 10/24/2016.
 */

enum class ConstantsApi {
    SIGN_UP,LOGIN,LOGIN_WITH_EMAIL, FORGET_PASSWORD,RESET_PASSWORD,CHECK_SENT_EMAIL_CODE,RESEND_EMAIL_VERIFICATION_LINK,
    CREATE_PROFILE, FETCH_PROFILE,FETCH_SELF_PROFILE, FETCH_FEEDS, FETCH_NEARBY, LOGOUT, SETTINGS, INTERESTED_PEOPLE, EVENT_LIKE,
    EVENT_INTERESTED, FAVORITE_EVENT, FAVORITE_USER, USER_LIKE, ALLOW_PUSH, ALLOW_EVENT, ALLOW_NSFW_SETTING, ALLOW_EVENT_UPDATE,
    CREATE_EVENT, UPDATE_LOCATION, UPDATE_NUMBER, SEARCH, EVENT, REASON, REPORT_EVENT, BLOCKED_USERS, BLOCK, UNBLOCK,
    NOTIFICATION, REPORT_USER, READ_NOTIFICATION, CLEAR_NOTIFICATION, DEACTIVATE, DEACTIVATE_LOGOUT, DELETE,
    SAVE_CHAT, FETCH_CHAT, CLEAR_CHAT, SEND_NOTIFICATION, CLEAR_BADGE, PRIVATE_ACCESS, SHARE_PRIVATE,
    UPLOAD_PRIVATE, PRIVATE_ALBUM, OTHER_PRIVATE_ALBUM, DELETE_PRIVATE, DELETE_NOTIFICATION,
    PRIVATE_ACCESS_OTHERS, REMOVE_PRIVATE, ADMIN_CONVERSATION, SEARCH_EVENTS, UNIT_IMPERIAL, UNIT_METRIC,UPADTE_TIME_STAMP,
    GET_MOST_RECENTLY_JOIND_USER, LIKE_USER_PROFILE_MULTIPLE_TIME,
    USER_PAYMENT,LIKE_USER_PROFILE_HEART,ADMIN_ADS,ADMIN_LAST_PUSH,SUPPORT_CLEARCHAT,REEGUR_UPDATENOTIFICATION,
    GET_CONNECTION_REQUEST, ACCEPT_CONNECTION_REQUEST,DECLINE_CONNECTION_REQUEST, SEND_CONNECTION_REQUEST,
    GET_MY_CONNECTIONS, CANCEL_SEND_CONNECTION_REQUEST, UNFRIEND_CONNECTION_REQUEST, USER_FAVOURIT_UNFAVOURIT,
    MACK_PROFILE_PRIVET,SAVE_USER_CONTACTS,MY_PRIVET_ALBUM_PERMISSION, SET_ACCESS_PRIVET_ALBUM_PERMISSION,
    FOLLOW_TO_USER, UNFOLLOW_USER, MY_FOLLOWER_LIST, MY_FOLLOWING_LIST, MY_LIKE_USER_LIST, ENABLE_DISABLE_NOTIFICATION_TYPE,
    GET_ALL_TYPE_NOTIFICATIONS, GET_TRANSECTION_HISTORY, GET_PROFILE_VISITORS_LIST, GET_FAVOURITE_USER_LIST, GET_LIKE_USER_LIST,
    GET_PLAN_LIST, GET_FOLLOWING_VISITORS_LIST, GET_EVENT_INTEREST_USER_LIST, GET_EVENT_LIKE_USER_LIST

}
